config/routes.rb
Rails3::Application.routes.draw do

  devise_for :users, :controllers => { :sessions => "user_sessions" },
    :path_names => { :sign_in => 'login', :sign_out => 'logout',  :registration => 'register' }

  resources :profiles

  resources :users do
     member do
       get :edit_password 
       get :set_login
       put :update_login
       put :update_password
       get :edit_email
       put :update_email
       get :edit_avatar
       put :update_avatar
    end
  end

  resources :announcements
  
  
  match  '/opensession' => "sessions#create", :as => "open_id_complete", :requirements => { :method => :get }
  match '/opencreate' => 'users#create',:as => :open_id_create,  :requirements => { :method => :get }
    
  
  namespace :admin do 
    root :to => 'dashboard#index'
    resources :settings 
    match '/settings/update_settings' => 'settings#update_settings',  :requirements => { :method => :post }
    resources :announcements
    resources :commits
    resources :delayed_jobs, :only => [:index]
    match '/users/search' => 'users#search',  :requirements => { :method => :get }
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email        
        match 'role/:role' => "users#toggle_role", :as => "toggle_role"
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end
  end
  
  match '/auth/:provider/callback' => 'authentications#create', :as => :auth_callback
  resources :authentications
  

  root :to => "dashboard#index"
  

end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  
  def index
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  # GET /
  # The default dashboard
  def index
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/views/admin/dashboard/_sidebar.html.erb
<h2><%= t('admin.options.user_managment')%></h2>

<ul>
	<li><%= link_to t('admin.users.options.manage'), admin_users_url %></li>
</ul>

<h2><%= t('admin.settings.title')%></h2>

<ul>
	<li><%= link_to t('admin.settings.options.manage', :app => configatron.site_name), admin_settings_url %></li>
</ul>

<h2><%= t('admin.announcements.title')%></h2>

<ul>
	<li><%= link_to t('admin.announcements.options.manage'), admin_announcements_url %></li>
</ul>

app/views/admin/dashboard/index.html.erb
<% content_for :header do -%>
	<%= configatron.site_name %> <%= t('admin.options.administration')%>
<% end -%>

<% content_for :sidebar do -%>
	<%= render :partial => 'admin/dashboard/sidebar' %>
<% end -%>

<h3><%= t('admin.dashboard.about.title')%>. </h3>

<p><%= t('admin.dashboard.about.text')%>.</p>