config/routes.rb
Rails3::Application.routes.draw do

  devise_for :users, :controllers => { :sessions => "user_sessions" },
    :path_names => { :sign_in => 'login', :sign_out => 'logout',  :registration => 'register' }

  resources :profiles

  resources :users do
     member do
       get :edit_password 
       get :set_login
       put :update_login
       put :update_password
       get :edit_email
       put :update_email
       get :edit_avatar
       put :update_avatar
    end
  end

  resources :announcements
  
  
  match  '/opensession' => "sessions#create", :as => "open_id_complete", :requirements => { :method => :get }
  match '/opencreate' => 'users#create',:as => :open_id_create,  :requirements => { :method => :get }
    
  
  namespace :admin do 
    root :to => 'dashboard#index'
    resources :settings 
    match '/settings/update_settings' => 'settings#update_settings',  :requirements => { :method => :post }
    resources :announcements
    resources :commits
    resources :delayed_jobs, :only => [:index]
    match '/users/search' => 'users#search',  :requirements => { :method => :get }
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email        
        match 'role/:role' => "users#toggle_role", :as => "toggle_role"
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end
  end
  
  match '/auth/:provider/callback' => 'authentications#create', :as => :auth_callback
  resources :authentications
  

  root :to => "dashboard#index"
  

end

app/models/user.rb
require 'aasm_roles'
class User < ActiveRecord::Base
  include AasmRoles
  
  devise :database_authenticatable, :recoverable, :registerable, :rememberable, :validatable, :trackable
  validates_uniqueness_of :login, :email, :case_sensitive => false
  
  # Relations
  has_and_belongs_to_many :roles
  has_one :profile
  has_many :authentications
  
  # Hooks
  after_create :create_profile, :register!

  attr_accessible :login, :email, :name, :password, :password_confirmation, :identity_url, :language
  before_validation(:set_default, :on => :create)
  
  def self.search(search, page)
    if search  
      paginate :per_page => 100, :page => page, :conditions => ['login LIKE ? OR email LIKE ?', "%#{search}%", "%#{search}%"]
    else  
      all
    end
  end
  
  def site_name
    self.login || self.email.split("@").first
  end
  
  def password_required?
    (authentications.empty? || !password.blank?) && super
  end
  
  def admin?
    has_role?(:admin)
  end
  
  def facebook?
    self.authentications.find_by_provider('facebook').present?
  end
  
  def has_role?(role)
    role_symbols.include?(role.to_sym) || role_symbols.include?(:admin)
  end
  
  def has_real_role?(role)
    role_symbols.include?(role.to_sym)
  end
  
  def role_symbols
    @role_symbols ||= roles.map {|r| r.name.underscore.to_sym }
  end

  def openid_login?
    !identity_url.blank? #|| (AppConfig.enable_facebook_auth && !facebook_id.blank?)
  end

  def twitter_login?
    !twitter_token.blank? && !twitter_secret.blank?
  end
  
  def not_using_openid?
    !openid_login?
  end
  
  def normalize_identity_url
    self.identity_url = OpenIdAuthentication.normalize_url(identity_url) if openid_login?
  rescue
    errors.add_to_base("Invalid OpenID URL")
  end
  
  def self.find_for_database_authentication(conditions={})
    self.where("login = ?", conditions[:login]).limit(1).first ||
      self.where("email = ?", conditions[:login]).limit(1).first
  end

  def apply_omniauth(omniauth)
    case omniauth['provider']
    when 'facebook'
      self.apply_facebook(omniauth)
    end
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'], :token =>(omniauth['credentials']['token'] rescue nil))
  end

  def facebook
    @fb_user ||= FbGraph::User.me(self.authentications.find_by_provider('facebook').token).fetch
  end

  protected
  
  def apply_facebook(omniauth)
    if (extra = omniauth['extra']['user_hash'] rescue false)
      self.email = (extra['email'] rescue '')
    end
  end
  
  def create_profile
    # Give the user a profile
    self.profile = Profile.create    
  end
  
  private
  
  def set_default

  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  
  %w(email login).each do |attr|
    in_place_edit_for :user, attr.to_sym
  end
  
  def toggle_role
    @user = User.find(params[:id])
    role = Role.find_by_name(params[:role])
    if @user.roles.include?(role)
      @user.roles.delete(role)
      flash[:notice] = "Granted #{role.name} permissions"
    else
      @user.roles << role
      @user.save
      flash[:notice] = "Revoked #{role.name} permissions"
    end
    if request.env["HTTP_REFERER"].present?
      redirect_to :back
    else
      redirect_to admin_user_path(@user)
    end
  end
  
  def search
    # Basic Search with pagination
    @users = User.search(params[:search], params[:page])
    render :index
  end
  
  def reset_password
    @user = User.find(params[:id])
    @user.reset_password!
    
    flash[:notice] = "A new password has been sent to the user by email."
    redirect_to admin_user_path(@user)
  end
  
  def pending
    @users = User.paginate :conditions => {:state => 'pending'}, :page => params[:page]
    render :action => 'index'
  end
  
  def suspended
    @users = User.paginate :conditions => {:state => 'suspended'}, :page => params[:page]
    render :action => 'index'
  end
  
  def active
    @users = User.paginate :conditions => {:state => 'active'}, :page => params[:page]
    render :action => 'index'
  end
  
  def deleted
    @users = User.paginate :conditions => {:state => 'deleted'}, :page => params[:page]
    render :action => 'index'
  end
  
  def activate
    @user = User.find(params[:id])
    @user.activate!
    redirect_to admin_users_path
  end
  
  def suspend
    @user = User.find(params[:id])
    @user.suspend! 
    redirect_to admin_users_path
  end

  def unsuspend
    @user = User.find(params[:id])
    @user.unsuspend! 
    redirect_to admin_users_path
  end

  def purge
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url
  end
  
  # DELETE /admin_users/1
  # DELETE /admin_users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.delete!

    redirect_to admin_users_path
  end

  # GET /admin_users
  # GET /admin_users.xml
  def index
    @users = User.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /admin_users/1
  # GET /admin_users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  def edit
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end    
  end
  
  # GET /admin_users/new
  # GET /admin_users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # POST /admin/users
  def create
    @user = User.new(params[:user])
   # debugger
    respond_to do |format|
      if @user.save
        flash[:notice] = "User was successfully created."
        format.html { redirect_to(admin_user_url(@user)) }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def update
    @user = User.find(params[:id])
    @user.attributes = params[:user]
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to :action => :show, :id => params[:id] }
      else
        format.html { render :action => :edit }
      end
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token
  
  before_filter :find_user, 
    :only => [:profile, 
              :edit_password,   :update_password, 
              :edit_email,      :update_email,
              :set_login ]
  
  layout 'login'
  
  def troubleshooting
    # Render troubleshooting.html.erb
    render :layout => 'login'
  end

  def clueless
    # These users are beyond our automated help...
    render :layout => 'login'
  end

  
  def edit_password
    if ! @user.not_using_openid?
      flash[:notice] = "You cannot update your password. You are using OpenID!"
      redirect_to :back
    end
    
    # render edit_password.html.erb
  end
  
  def update_password    
    if !@user.not_using_openid?
      flash[:notice] = "You cannot update your password. You are using OpenID!"
      redirect_to :back
    end
    if @user.update_with_password(params[:user])
      redirect_to root_path, :notice => "Password updated!"
    else
      @user.errors.each do |name ,msg| 
        flash[:error] = name.to_s.titleize + " " + msg
      end
      render :edit_password        
    end
 
  end
  
  def edit_email
    if ! @user.not_using_openid?
      flash[:notice] = "You cannot update your email address. You are using OpenID!"
      redirect_to :back
    end
    
    # render edit_email.html.erb
  end
  
  def update_email
    if ! @user.not_using_openid?
      flash[:notice] = "You cannot update your email address. You are using OpenID!"
      redirect_to :back
    end
    
    if current_user == @user
      if @user.update_attributes(:email => params[:email])
        flash[:notice] = "Your email address has been updated."
        redirect_to profile_url(@user)
      else
        flash[:error] = "Your email address could not be updated."
        redirect_to edit_email_user_url(@user)
      end
    else

      flash[:error] = "You cannot update another user's email address!"
      redirect_to edit_email_user_url(@user)
    end
  end  
  
  def set_login

  end
  
  def update_login
    if @user.login.present?
      flash[:notice] = "You cannot update your login. If you still want so please contact site administrator!"
      redirect_to :back
    end
    
    if current_user == @user
      if @user.update_attributes(:login => params[:login])
        flash[:notice] = "Your login has been updated."
        redirect_to profile_url(@user)
      else
        flash[:error] = "Your login could not be updated."
        redirect_to set_login_user_url(@user)
      end
    else

      flash[:error] = "You cannot update another user's email address!"
      redirect_to edit_email_user_url(@user)
    end
  end
  
  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    current_user.delete!
    
    logout_killing_session!
    
    flash[:notice] = "Your account has been removed."
    redirect_back_or_default(root_path)
  end  
  
  protected

  def find_user
    @user = User.find(params[:id])
  end

  def create_new_user(attributes)
    @user = User.new(attributes)
    if @user && @user.valid?
      if @user.not_using_openid?
        @user.register!
      else
        @user.register_openid!
      end
    end
    
    if @user.errors.empty?
      successful_creation(@user)
    else
      failed_creation
    end
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/users/clueless.html.erb
<% content_for :header do -%>
	Account Amnesia
<% end -%>

<p>
	You have indicated you can't remember your <%= configatron.site_name %> account at all.
</p>

<p>
	We can't help you directly to recover you account. Please contact <%= configatron.support_name %> at <%= secure_mail_to configatron.support_email %> for more help.
</p>

<p>
	If you don't have any important data in your account, you may also opt for <%= link_to "registering a new account", signup_url %>.
</p>

app/views/users/edit_email.html.erb
<% content_for :header do -%>
	Change my email address
<% end -%>

<%= form_for @user, :url => update_email_user_url(@user), :html => {:method => :put} do |f| %>

	<h3>Your new email address</h3>

	<p>Please enter your new email address below. Please double-check it, because you may need it later to retrieve your password.</p>

	<p><%= text_field_tag 'email', '', :size => 20 %></p>

	<p><%= submit_tag "Change my email address" %> or <%= link_to "forget about it", profile_url(@user) %></p>
	
<% end %>

app/views/users/edit_password.html.erb
<% content_for :header do -%>
	Change my password
<% end -%>

<%= form_for @user,  :url => update_password_user_url(@user), :html => {:method => :put} do |f| %>

	<h3>Your current password</h3>

	<p>To prevent abuse, please enter your current password.</p>

	<p><%= password_field_tag 'user[current_password]', '', :size => 20 %></p>

	<h3>Your new password</h3>

	<p>Please enter your new password (and the confirmation) below.</p>

	<p><%= password_field_tag 'user[password]', '', :size => 20 %></p>

	<p><%= password_field_tag 'user[password_confirmation]', '', :size => 20 %></p>

	<p><%= submit_tag "Change my password" %> or <%= link_to "forget about it", profile_url(@user) %></p>
	
<% end %>

app/views/users/forgot_login.html.erb
<% content_for :header do -%>
	Login Recovery
<% end -%>

<% unless @user.nil? %>
	<p>An email containing your <%= configatron.site_name %> account's login has been dispatched to you at <em><%= @user.email %></em>.</p>
	
	<div id="submitbutton">
		<p><%= link_to "Login now &raquo;", login_url %></p>
	</div>
<% else %>
	<p>Please enter the email address associated with your account. We will send you an email with your login shortly.</p>

	<%= form_tag user_forgot_login_url, :method => :put do %>
		<p><label>Your email address</label><br />
		<%= text_field_tag :email %></p>
	
		<div id="submitbutton">
			<p><%= submit_tag 'Send me my login &raquo;' %></p>
		</div>
	<% end %>
<% end %>

app/views/users/forgot_password.html.erb
<% content_for :header do -%>
	Password Recovery
<% end -%>

<% unless @user.nil? %>
	<% if @user.active? %>
		<p>An email containing further instructions has been dispatched to you at <em><%= @user.email %></em>.</p>
		<p>Please follow the instructions in the email to recover your account's password.</p> 
	<% else %>
		<p>Your account is currently not active. You cannot reset your password when your account is not active.</p>
		<p>Please contact <%= configatron.support_name %> at <%= secure_mail_to configatron.support_email %>
	<% end %>
<% else %>
	<p>Please enter the login or email address associated with your account. We will send you an email with further instructions shortly.</p>

	<%= form_tag user_forgot_password_url, :method => :put do %>
		<p><label>Your login or email address</label><br />
		<%= text_field_tag :email_or_login %></p>
	
		<div id="submitbutton">
			<p><%= submit_tag 'Recover my password &raquo;' %></p>
		</div>
	<% end %>
<% end %>

app/views/users/reset_password.html.erb
<% content_for :header do -%>
	Password Recovery
<% end -%>

<% unless @user.nil? || !@user.active? %>
	<p>
		You have successfully reset your password. You will receive an email with your new password shortly.
	</p>
	
	<p>
		<strong>Note: After you login, please change your password to a more secure and easier to remember password.</strong>
	</p>
	
	<div id="submitbutton">
		<p><%= link_to "Login now &raquo;", login_url %></p>
	</div>
<% else %>
	<p>
		We're sorry, but we couldn't reset your password for you.
	</p>
	
	<p>
		To obtain a new password, please contact <%= configatron.support_name %> at <%= secure_mail_to configatron.support_email %>.
	</p>
<% end %>

app/views/users/set_login.html.erb
<% content_for :header do -%>
  <%= t('site.profile.actions.set_login')%>
<% end -%>

<%= form_for @user, :url => update_login_user_url(@user), :html => {:method => :put} do |f| %>

	<h3><%= t('site.profile.login.new')%></h3>

	<p><%= t('site.profile.login.text')%></p>

	<p><%= text_field_tag 'login', '', :size => 20 %></p>

	<p><%= submit_tag t('site.profile.login.set') %> <%= t('words.or')%> <%= link_to t('manage.forget_about_it'), profile_url(@user) %></p>
	
<% end %>

app/views/users/troubleshooting.html.erb
<% content_for :header do -%>
	What seems to be the problem?
<% end -%>

<p>
	You have indicated you are having trouble logging in to <%= configatron.site_name %>. What seems to be the problem?
</p>

<ul>
	<li><%= link_to "I don't remember my password", user_forgot_password_url %></li>
	<li><%= link_to "I forgot my login, but I know my email", user_forgot_login_url %></li>
	<li><%= link_to "I don't remember my login, email or password!", user_clueless_url %></li>
</ul>

<p>
	<%= link_to "&laquo; Go back", login_url %>
</p>