config/routes.rb
Rails3::Application.routes.draw do

  devise_for :users, :controllers => { :sessions => "user_sessions" },
    :path_names => { :sign_in => 'login', :sign_out => 'logout',  :registration => 'register' }

  resources :profiles

  resources :users do
     member do
       get :edit_password 
       get :set_login
       put :update_login
       put :update_password
       get :edit_email
       put :update_email
       get :edit_avatar
       put :update_avatar
    end
  end

  resources :announcements
  
  
  match  '/opensession' => "sessions#create", :as => "open_id_complete", :requirements => { :method => :get }
  match '/opencreate' => 'users#create',:as => :open_id_create,  :requirements => { :method => :get }
    
  
  namespace :admin do 
    root :to => 'dashboard#index'
    resources :settings 
    match '/settings/update_settings' => 'settings#update_settings',  :requirements => { :method => :post }
    resources :announcements
    resources :commits
    resources :delayed_jobs, :only => [:index]
    match '/users/search' => 'users#search',  :requirements => { :method => :get }
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email        
        match 'role/:role' => "users#toggle_role", :as => "toggle_role"
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end
  end
  
  match '/auth/:provider/callback' => 'authentications#create', :as => :auth_callback
  resources :authentications
  

  root :to => "dashboard#index"
  

end

app/models/announcement.rb
class Announcement < ActiveRecord::Base
  scope :active, lambda { 
    where("starts_at <= ? AND ends_at >= ?", Time.now.utc, Time.now.utc) 
  }    
  scope :since, lambda { |hide_time|  
    where("updated_at > ? OR starts_at > ?", hide_time.utc, hide_time.utc) if hide_time
  }
  
  def self.display(hide_time)
    active.since(hide_time)
  end

end

app/controllers/admin/announcements_controller.rb
class Admin::AnnouncementsController < Admin::BaseController
  
  # GET /announcements
  # GET /announcements.xml
  def index
    @announcements = Announcement.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @announcements }
    end
  end

  # GET /announcements/1
  # GET /announcements/1.xml
  def show
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/new
  # GET /announcements/new.xml
  def new
    @announcement = Announcement.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @announcement }
    end
  end

  # GET /announcements/1/edit
  def edit
    @announcement = Announcement.find(params[:id])
  end

  # POST /announcements
  # POST /announcements.xml
  def create
    @announcement = Announcement.new(params[:announcement])

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to(admin_announcements_path, :notice => 'Announcement was successfully created.') }
        format.xml  { render :xml => @announcement, :status => :created, :location => @announcement }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /announcements/1
  # PUT /announcements/1.xml
  def update
    @announcement = Announcement.find(params[:id])

    respond_to do |format|
      if @announcement.update_attributes(params[:announcement])
        format.html { redirect_to(admin_announcements_path, :notice => 'Announcement was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @announcement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1
  # DELETE /announcements/1.xml
  def destroy
    @announcement = Announcement.find(params[:id])
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to(admin_announcements_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
  def announcements_for_display
    @announcements_for_display ||= Announcement.display(session[:announcement_hide_time])
  end
  
  def announcements_link_label
    return "Hide " + (@announcements_for_display.size == 1 ? "announcement" : "announcements") + "."
  end  
end

app/views/admin/announcements/_form.html.erb
<%= f.input :headline, :as => :string %>
<%= f.input :message %>
<%= f.input :starts_at %>
<%= f.input :ends_at %>
<%= f.button :submit %>

app/views/admin/announcements/edit.html.erb
<% content_for :header do -%>
	<%= t('.title')%>
<% end -%>

<%= simple_form_for @announcement do |f| %>
  <%= render :partial => 'form', :locals => {:f => f}%>
<% end %>


<%= link_to t('manage.show'), admin_announcement_path(@announcement) %> |
<%= link_to t('back'), admin_announcements_path %>

app/views/admin/announcements/index.html.erb
<% content_for :header do -%>
	<%= t('admin.announcements.title')%>
<% end -%>

<table class="index">
  <tr>
    <th><%= t('activerecord.attributes.announcement.headline')%></th>
    <th><%= t('activerecord.attributes.announcement.message')%></th>
    <th><%= t('activerecord.attributes.announcement.starts_at')%></th>
    <th><%= t('activerecord.attributes.announcement.ends_at')%></th>
  </tr>

<% @announcements.each do |announcement| %>
  <tr>
    <td><%=h announcement.headline %></td>
    <td><%=h announcement.message %></td>
    <td><%=h announcement.starts_at %></td>
    <td><%=h announcement.ends_at %></td>
    <td><%= link_to t('manage.show'), admin_announcement_path(announcement) %></td>
    <td><%= link_to t('manage.edit'), edit_admin_announcement_path(announcement) %></td>
    <td><%= link_to t('manage.destroy'), admin_announcement_path(announcement), :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to t('.options.new'), new_admin_announcement_path %>

app/views/admin/announcements/new.html.erb
<% content_for :header do -%>
	<%= t('.title')%>
<% end -%>

<%= simple_form_for @announcement,:url => admin_announcements_path do |f| %>
  <%= render :partial => 'form', :locals => {:f => f}%>
<% end %>

<%= link_to t('back'), admin_announcements_path %>

app/views/admin/announcements/show.html.erb
<% content_for :header do -%>
	Announcements
<% end -%>

<p>
  <b>Headline:</b>
  <%=h @announcement.headline %>
</p>

<p>
  <b>Message:</b>
  <%=h @announcement.message %>
</p>

<p>
  <b>Starts at:</b>
  <%=h @announcement.starts_at %>
</p>

<p>
  <b>Ends at:</b>
  <%=h @announcement.ends_at %>
</p>


<%= link_to 'Edit', edit_admin_announcement_path(@announcement) %> |
<%= link_to t('back'), admin_announcements_path %>