config/routes.rb
Rails3::Application.routes.draw do

  devise_for :users, :controllers => { :sessions => "user_sessions" },
    :path_names => { :sign_in => 'login', :sign_out => 'logout',  :registration => 'register' }

  resources :profiles

  resources :users do
     member do
       get :edit_password 
       get :set_login
       put :update_login
       put :update_password
       get :edit_email
       put :update_email
       get :edit_avatar
       put :update_avatar
    end
  end

  resources :announcements
  
  
  match  '/opensession' => "sessions#create", :as => "open_id_complete", :requirements => { :method => :get }
  match '/opencreate' => 'users#create',:as => :open_id_create,  :requirements => { :method => :get }
    
  
  namespace :admin do 
    root :to => 'dashboard#index'
    resources :settings 
    match '/settings/update_settings' => 'settings#update_settings',  :requirements => { :method => :post }
    resources :announcements
    resources :commits
    resources :delayed_jobs, :only => [:index]
    match '/users/search' => 'users#search',  :requirements => { :method => :get }
    resources :users do 
      member do 
        put :suspend
        put :unsuspend
        put :activate
        delete :purge
        put :reset_password
        get :set_user_login
        get :set_user_email        
        match 'role/:role' => "users#toggle_role", :as => "toggle_role"
      end
      collection do
        get :pending
        get :active
        get :suspended
        get :deleted
      end
    end
  end
  
  match '/auth/:provider/callback' => 'authentications#create', :as => :auth_callback
  resources :authentications
  

  root :to => "dashboard#index"
  

end

app/models/user.rb
require 'aasm_roles'
class User < ActiveRecord::Base
  include AasmRoles
  
  devise :database_authenticatable, :recoverable, :registerable, :rememberable, :validatable, :trackable
  validates_uniqueness_of :login, :email, :case_sensitive => false
  
  # Relations
  has_and_belongs_to_many :roles
  has_one :profile
  has_many :authentications
  
  # Hooks
  after_create :create_profile, :register!

  attr_accessible :login, :email, :name, :password, :password_confirmation, :identity_url, :language
  before_validation(:set_default, :on => :create)
  
  def self.search(search, page)
    if search  
      paginate :per_page => 100, :page => page, :conditions => ['login LIKE ? OR email LIKE ?', "%#{search}%", "%#{search}%"]
    else  
      all
    end
  end
  
  def site_name
    self.login || self.email.split("@").first
  end
  
  def password_required?
    (authentications.empty? || !password.blank?) && super
  end
  
  def admin?
    has_role?(:admin)
  end
  
  def facebook?
    self.authentications.find_by_provider('facebook').present?
  end
  
  def has_role?(role)
    role_symbols.include?(role.to_sym) || role_symbols.include?(:admin)
  end
  
  def has_real_role?(role)
    role_symbols.include?(role.to_sym)
  end
  
  def role_symbols
    @role_symbols ||= roles.map {|r| r.name.underscore.to_sym }
  end

  def openid_login?
    !identity_url.blank? #|| (AppConfig.enable_facebook_auth && !facebook_id.blank?)
  end

  def twitter_login?
    !twitter_token.blank? && !twitter_secret.blank?
  end
  
  def not_using_openid?
    !openid_login?
  end
  
  def normalize_identity_url
    self.identity_url = OpenIdAuthentication.normalize_url(identity_url) if openid_login?
  rescue
    errors.add_to_base("Invalid OpenID URL")
  end
  
  def self.find_for_database_authentication(conditions={})
    self.where("login = ?", conditions[:login]).limit(1).first ||
      self.where("email = ?", conditions[:login]).limit(1).first
  end

  def apply_omniauth(omniauth)
    case omniauth['provider']
    when 'facebook'
      self.apply_facebook(omniauth)
    end
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'], :token =>(omniauth['credentials']['token'] rescue nil))
  end

  def facebook
    @fb_user ||= FbGraph::User.me(self.authentications.find_by_provider('facebook').token).fetch
  end

  protected
  
  def apply_facebook(omniauth)
    if (extra = omniauth['extra']['user_hash'] rescue false)
      self.email = (extra['email'] rescue '')
    end
  end
  
  def create_profile
    # Give the user a profile
    self.profile = Profile.create    
  end
  
  private
  
  def set_default

  end
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  
  %w(email login).each do |attr|
    in_place_edit_for :user, attr.to_sym
  end
  
  def toggle_role
    @user = User.find(params[:id])
    role = Role.find_by_name(params[:role])
    if @user.roles.include?(role)
      @user.roles.delete(role)
      flash[:notice] = "Granted #{role.name} permissions"
    else
      @user.roles << role
      @user.save
      flash[:notice] = "Revoked #{role.name} permissions"
    end
    if request.env["HTTP_REFERER"].present?
      redirect_to :back
    else
      redirect_to admin_user_path(@user)
    end
  end
  
  def search
    # Basic Search with pagination
    @users = User.search(params[:search], params[:page])
    render :index
  end
  
  def reset_password
    @user = User.find(params[:id])
    @user.reset_password!
    
    flash[:notice] = "A new password has been sent to the user by email."
    redirect_to admin_user_path(@user)
  end
  
  def pending
    @users = User.paginate :conditions => {:state => 'pending'}, :page => params[:page]
    render :action => 'index'
  end
  
  def suspended
    @users = User.paginate :conditions => {:state => 'suspended'}, :page => params[:page]
    render :action => 'index'
  end
  
  def active
    @users = User.paginate :conditions => {:state => 'active'}, :page => params[:page]
    render :action => 'index'
  end
  
  def deleted
    @users = User.paginate :conditions => {:state => 'deleted'}, :page => params[:page]
    render :action => 'index'
  end
  
  def activate
    @user = User.find(params[:id])
    @user.activate!
    redirect_to admin_users_path
  end
  
  def suspend
    @user = User.find(params[:id])
    @user.suspend! 
    redirect_to admin_users_path
  end

  def unsuspend
    @user = User.find(params[:id])
    @user.unsuspend! 
    redirect_to admin_users_path
  end

  def purge
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url
  end
  
  # DELETE /admin_users/1
  # DELETE /admin_users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.delete!

    redirect_to admin_users_path
  end

  # GET /admin_users
  # GET /admin_users.xml
  def index
    @users = User.paginate(:page => params[:page])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
    end
  end

  # GET /admin_users/1
  # GET /admin_users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  def edit
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end    
  end
  
  # GET /admin_users/new
  # GET /admin_users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # POST /admin/users
  def create
    @user = User.new(params[:user])
   # debugger
    respond_to do |format|
      if @user.save
        flash[:notice] = "User was successfully created."
        format.html { redirect_to(admin_user_url(@user)) }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def update
    @user = User.find(params[:id])
    @user.attributes = params[:user]
    
    respond_to do |format|
      if @user.save
        format.html { redirect_to :action => :show, :id => params[:id] }
      else
        format.html { render :action => :edit }
      end
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :verify_authenticity_token
  
  before_filter :find_user, 
    :only => [:profile, 
              :edit_password,   :update_password, 
              :edit_email,      :update_email,
              :set_login ]
  
  layout 'login'
  
  def troubleshooting
    # Render troubleshooting.html.erb
    render :layout => 'login'
  end

  def clueless
    # These users are beyond our automated help...
    render :layout => 'login'
  end

  
  def edit_password
    if ! @user.not_using_openid?
      flash[:notice] = "You cannot update your password. You are using OpenID!"
      redirect_to :back
    end
    
    # render edit_password.html.erb
  end
  
  def update_password    
    if !@user.not_using_openid?
      flash[:notice] = "You cannot update your password. You are using OpenID!"
      redirect_to :back
    end
    if @user.update_with_password(params[:user])
      redirect_to root_path, :notice => "Password updated!"
    else
      @user.errors.each do |name ,msg| 
        flash[:error] = name.to_s.titleize + " " + msg
      end
      render :edit_password        
    end
 
  end
  
  def edit_email
    if ! @user.not_using_openid?
      flash[:notice] = "You cannot update your email address. You are using OpenID!"
      redirect_to :back
    end
    
    # render edit_email.html.erb
  end
  
  def update_email
    if ! @user.not_using_openid?
      flash[:notice] = "You cannot update your email address. You are using OpenID!"
      redirect_to :back
    end
    
    if current_user == @user
      if @user.update_attributes(:email => params[:email])
        flash[:notice] = "Your email address has been updated."
        redirect_to profile_url(@user)
      else
        flash[:error] = "Your email address could not be updated."
        redirect_to edit_email_user_url(@user)
      end
    else

      flash[:error] = "You cannot update another user's email address!"
      redirect_to edit_email_user_url(@user)
    end
  end  
  
  def set_login

  end
  
  def update_login
    if @user.login.present?
      flash[:notice] = "You cannot update your login. If you still want so please contact site administrator!"
      redirect_to :back
    end
    
    if current_user == @user
      if @user.update_attributes(:login => params[:login])
        flash[:notice] = "Your login has been updated."
        redirect_to profile_url(@user)
      else
        flash[:error] = "Your login could not be updated."
        redirect_to set_login_user_url(@user)
      end
    else

      flash[:error] = "You cannot update another user's email address!"
      redirect_to edit_email_user_url(@user)
    end
  end
  
  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    current_user.delete!
    
    logout_killing_session!
    
    flash[:notice] = "Your account has been removed."
    redirect_back_or_default(root_path)
  end  
  
  protected

  def find_user
    @user = User.find(params[:id])
  end

  def create_new_user(attributes)
    @user = User.new(attributes)
    if @user && @user.valid?
      if @user.not_using_openid?
        @user.register!
      else
        @user.register_openid!
      end
    end
    
    if @user.errors.empty?
      successful_creation(@user)
    else
      failed_creation
    end
  end
  
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/views/admin/users/edit.html.erb
<% content_for :header do -%>
Edit User
<% end -%>

<% content_for :sidebar do -%>
    <%= render "admin/shared/error_messages", :target => @user%>
<% end -%>

<%= form_for [:admin, @user], :method => :put do |f| -%>
<table class="overview">
<%= cell((f.label :login), (f.text_field :login))%>
<%= cell((f.label :email), (f.text_field :email))%>
<%= cell((f.label :password), (f.password_field :password))%>
<%= cell((f.label :password_confirmation), (f.password_field :password_confirmation))%>
<%= cell((f.label :language), (f.select(:language, [['English', 'en'], ['Polski', 'pl']])))%>


<%= cell("", (submit_tag 'Create account'))%>
<% end -%>
<%= cell("", (link_to t('back'), admin_users_path))%>
</table>

app/views/admin/users/index.html.erb
<% content_for :header do -%>
	<%= t('admin.users.title', :app => configatron.site_name) %>
<% end -%>
  
<% content_for :sidebar do -%>
    <h2><%= t('.search') %></h2>
	<ul>
	    <li>
	        <%= form_tag admin_users_search_path, :method => 'get' do %>
            <%= text_field_tag :search, params[:search], :type => "" , :results => 5, :placeholder =>  t('.search_by') %>
            <%= submit_tag  t('.search'), :name => nil %>
            <% end %>
        </li>
    </ul>
    <h2><%= t('.filtr') %></h2>
    <ul>
		<li><%= link_to t('.options.all'), admin_users_url %></li>
		<li><%= link_to t('.options.active'), active_admin_users_url %></li>
		<li><%= link_to t('.options.suspended'), suspended_admin_users_url %></li>
		<li><%= link_to t('.options.pending'), pending_admin_users_url %></li>
		<li><%= link_to t('.options.deleted'), deleted_admin_users_url %></li>
	</ul>
<% end -%>

<table class="index">
  <tr>
	<th>ID</th>
	<th><%= t('activerecord.attributes.user.login')%></th>
	<th><%= t('activerecord.attributes.user.email')%></th>
	<th><%= t('activerecord.attributes.user.status')%></th>
	<th><%= t('activerecord.attributes.user.facebook')%></th>
	<th><%= t('activerecord.attributes.user.admin')%></th>
  </tr>
  
<p><%= t('.display', :count => @users.count)%></p>

<% for user in @users %>

	
  <tr>
	<td><%= user.id %></td>
	<td><%= link_to h(user.login || user.site_name), admin_user_url(user) %></td>
	<td><%= user.email %></td>
	<td><%= user.state %></td>
	<td><%= t('misc.words.yes') if user.facebook? %></td>
	<td><%= t('misc.words.yes') if user.admin? %></td>
    <td class="actions">
		<% if user.pending? %>
			<%= link_to t('admin.users.options.activate'), activate_admin_user_url(user), :method => :put %>
			<%= link_to t('admin.users.options.suspend'), suspend_admin_user_url(user), :method => :put %>
			<%= link_to t('admin.users.options.delete'), admin_user_url(user), :method => :delete, :confirm => "Are you sure?" %>
		<% elsif user.passive? %>
			<%= link_to t('admin.users.options.activate'), activate_admin_user_url(user), :method => :put %>
			<%= link_to t('admin.users.options.suspend'), suspend_admin_user_path(user), :method => :put %>
			<%= link_to t('admin.users.options.delete'), admin_user_url(user), :method => :delete, :confirm => "Are you sure?" %>
		<% elsif user.active? %>
			<%= link_to t('admin.users.options.suspend'), suspend_admin_user_path(user), :method => :put  %>
			<%= link_to t('admin.users.options.delete'), admin_user_url(user), :method => :delete, :confirm => "Are you sure?" %>
		<% elsif user.suspended? %>
			<%= link_to t('admin.users.options.unsuspend'), unsuspend_admin_user_url(user), :method => :put %>
			<%= link_to t('admin.users.options.delete'), admin_user_url(user), :method => :delete, :confirm => "Are you sure?" %>		
		<% end %>
	</td>
  </tr>
<% end %>
</table>

<%= will_paginate @users %>

<p>
	<%= link_to t('admin.users.options.new'), new_admin_user_path %>
</p>

app/views/admin/users/new.html.erb
<% content_for :header do -%>
Create a new <%= configatron.site_name %> account
<% end -%>

<% content_for :sidebar do -%>
    <%= render "admin/shared/error_messages", :target => @user%>
<% end -%>

<%= form_for :user, :url => admin_users_path do |f| -%>
<table class="overview">
<%= cell((f.label :login), (f.text_field :login))%>
<%= cell((f.label :email), (f.text_field :email))%>
<%= cell((f.label :password), (f.password_field :password))%>
<%= cell((f.label :password_confirmation), (f.password_field :password_confirmation))%>
<%= cell((f.label :language), (f.select(:language, [['English', 'en'], ['Polski', 'pl']])))%>

<%= cell("", (submit_tag 'Create account'))%>
<%= cell("", (link_to t('back'), admin_users_path))%>
</table>

<% end -%>

app/views/admin/users/show.html.erb
<% content_for :header do -%>
 	<%= t('.title', :login => @user.login) %></em>
<% end -%>

<% content_for :sidebar do -%>

<h2><%= t('.status', :status => @user.state.to_s.humanize) %></h2>	

<ul>
	<% if @user.pending? -%>
		<li><%= link_to t('admin.users.options.activate'), activate_admin_user_url(@user), :method => :put %></li>
		<li><%= link_to t('admin.users.options.suspend'), suspend_admin_user_url(@user), :method => :put %></li>
		<li><%= link_to t('admin.users.options.delete'), admin_user_url(@user), :method => :delete %></li>
	<% end -%>
	
	<% if @user.suspended? -%>
		<li><%= link_to t('admin.users.options.suspend'), unsuspend_admin_user_url(@user), :method => :put %></li>
	<% end -%>

	<% if @user.active? -%>
		<li><%= link_to t('admin.users.options.suspend'), suspend_admin_user_url(@user), :method => :put %></li>
		<li><%= link_to t('admin.users.options.delete'), admin_user_url(@user), :method => :delete, :confirm => "Are you sure you want to delete this account?" %></li>
	<% end -%>
	
	<% # TODO: Uncomment to enable user purging by the administrator %>
	<!--
	<% if @user.deleted? -%>
		<li><%= link_to "Purge", purge_admin_user_url(@user), :method => :delete, :confirm => "Are you sure you want to remove this account, and all data associated with it from base_app?" %></li>
	<% end -%>
    -->
</ul>	

<h2><%= t('admin.users.options.roles') %></h2>	

<ul>
	<% Role.all.each do |x| -%>
		<li>
		<%= link_to (@user.has_real_role?(x.name.underscore.to_sym) ? t('.take', :role => x.name.humanize.gsub(/-/, ' ')) : t('.grant', :role => x.name.humanize.gsub(/-/, ' '))), toggle_role_admin_user_path(@user, x.name), :method => :post %>
		</li>
	<% end -%>
</ul>
<% end -%>

<table class="overview">
  <% if @user.login.present? %>
  	<%= cell t('activerecord.attributes.user.login'), "#{in_place_editor_field :user, 'login'}" %>
  <% else %>
    <%= cell t('activerecord.attributes.user.language'), h(@user.site_name) %>
  <% end %>
	<%= cell "ID", h(@user.id) %>
	<%= cell t('activerecord.attributes.user.language'), h(@user.language) %>
	<%= cell t('activerecord.attributes.user.facebook'), (t('misc.words.yes') if @user.facebook?) %>

	<%= cell t('activerecord.attributes.user.roles'), @user.roles.map{|x| x.name.humanize }.join(", ") %>
	

	<%= cell_separator %>
	
	<%= cell t('activerecord.attributes.user.email'), "#{in_place_editor_field :user, 'email'}" %>
	<%= cell t('activerecord.attributes.user.password'), "#{"*"*8} <small>#{link_to_if !@user.deleted?, t('admin.users.options.send_password'), reset_password_admin_user_url(@user), :method => :put}</small>" %>
	
	<%= cell_separator %>
	
	<%= cell t('activerecord.attributes.user.created_at'), l(@user.created_at, :format => :long) %>
	<%= cell t('activerecord.attributes.user.updated_at'), l(@user.updated_at, :format => :long) %>
</table>

<%= link_to t('manage.edit'), edit_admin_user_path(@user) %> |
<%= link_to t('back'), admin_users_path %>